name: mlhc_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - statsmodels
  - pip

  - pip:
      - torch==2.4.1
      - DateTime==5.5
      - igraph==0.11.8
      - ipdb==0.13.13
      - scanpy==1.10.3
      - scikit-bio==0.6.2
      - tensorboard==2.20.0
      - umap==0.1.1