name: mlhc_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - pandas
  - pip

  - pip:
      - torch==2.4.1
      - ipdb==0.13.13
      - scikit-learn==1.5.2
      - scipy==1.14.1
      - tensorboard==2.20.0
      - matplotlib==3.9.2
      - tqdm==4.66.5
      - joblib==1.4.2